### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by KRIEZIEY** [De-eloper/njRAT-All-Versions#1]
![Builder_F69GzwbXLI](https://user-images.githubusercontent.com/102611940/202875254-f094b9e6-b7a7-40b5-87da-d5988039bd53.png)

when i reinstalled win 11 it started to give me error mayby i need ti install some components or something like that?
(not only in this rat this problem is in any rat)

**Comment by De-eloper** [comment]
I am unsure of this error, the 1st issue you might need t o have added an exclusion to windows defender or antivirus (Or turn it off temporarily to build). Or it could also be that most NjRat versions use .NET Framework 2.0 to build, so possibly you are missing .NET 2.0. (As it is an old version, possibly it is not included in Win 11.)

**Comment by De-eloper** [comment]
If you can, try follow this article to see if it works:
https://www.groovypost.com/howto/enable-net-framework-2-0-and-3-5-windows-11/

**Comment by KRIEZIEY** [comment]
thanks it worked
